-- Add meeting_type and meeting_url columns to meetings table
ALTER TABLE meetings
ADD COLUMN meeting_type TEXT DEFAULT 'manual',
ADD COLUMN meeting_url TEXT;

-- Update existing meetings to have manual meeting type
UPDATE meetings
SET meeting_type = 'manual'
WHERE meeting_type IS NULL;

-- Add index on meeting_type for faster queries
CREATE INDEX idx_meetings_meeting_type ON meetings(meeting_type);

-- Add comment to explain the meeting_type column
COMMENT ON COLUMN meetings.meeting_type IS 'Type of meeting link: manual or google_meet';
COMMENT ON COLUMN meetings.meeting_url IS 'URL for the meeting, either manually entered or generated by Google Meet'; 