
-- Since the columns already exist from the previous migration, let's ensure they are properly set up
-- This will update the database schema to match what the code expects

-- Verify and ensure the meeting_type and meeting_url columns exist
DO $$
BEGIN
    -- Add meeting_type column if it doesn't exist
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'meetings' 
        AND column_name = 'meeting_type'
    ) THEN
        ALTER TABLE meetings ADD COLUMN meeting_type TEXT DEFAULT 'manual';
    END IF;

    -- Add meeting_url column if it doesn't exist  
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'meetings' 
        AND column_name = 'meeting_url'
    ) THEN
        ALTER TABLE meetings ADD COLUMN meeting_url TEXT;
    END IF;
END $$;

-- Add index on meeting_type for faster queries if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes 
        WHERE tablename = 'meetings' 
        AND indexname = 'idx_meetings_meeting_type'
    ) THEN
        CREATE INDEX idx_meetings_meeting_type ON meetings(meeting_type);
    END IF;
END $$;

-- Add comments to explain the columns
COMMENT ON COLUMN meetings.meeting_type IS 'Type of meeting link: manual or google_meet';
COMMENT ON COLUMN meetings.meeting_url IS 'URL for the meeting, either manually entered or generated by Google Meet';
